name: build-project
description: 'Build Project'
inputs:
  env:
    required: true
    description: The target environment
  version:
    required: true
    description: Version to build

runs:
  using: composite
  steps:
    - name: Deploy
      shell: bash
      run: |
        echo Deploy version ${{ inputs.version }} to ${{ github.env }}
