name: build-project
description: 'Build Project'
inputs:
  version:
    required: true
    description: Version to build
  publish-image:
    default: "false"
    description: Publish image
  token:
    description: GitHub token

runs:
  using: composite
  steps:
    - name: Build
      shell: bash
      run: |
        mvn -X --batch-mode --update-snapshots verify spring-boot:build-image -Drevision="${{ inputs.version }}" -Dpublish.image=${{ inputs.publish-image }} -Ddocker.username="${{ github.actor }}" -Ddocker.password="${{ inputs.token }}"
    - name: SonarQube
      shell: bash
      run: "echo TODO: SonarQube"
    - name: Upload Build Reports
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-reports
        path: '**/target/surefire-reports/'
