name: Build Main
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - none
          - dev
          - test
          - qa
        default: qa
        description: Deploy to environment?

jobs:
  build:
    name: 'Build'
    if: github.ref == 'refs/heads/main'
    uses: hwolf/test/.github/workflows/build-and-test.yml@test-1
    with:
      revision: "$(date +%Y%m%d)-${{ github.run_number }}"

  deploy:
    name: 'Deploy'
    if: github.ref == 'refs/heads/main' && inputs.environment != 'none'
    needs:
      - build
    uses: hwolf/test/.github/workflows/deploy.yml@test-1
    with:
      image-name: "${{ needs.build.outputs.image-name }}"
      environment: "${{ inputs.environment || 'qa' }}"
