name: "Build Main"
on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build"
    if: github.ref == 'refs/heads/main'
    uses: hwolf/workflows/.github/workflows/build.yml@main
    with:
      environment: "qa"
    secrets: inherit
