name: "Build Main"
on:
  push:
    branches:
      - main

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(secrets) }}"

  build:
    name: "Build"
    if: github.ref == 'refs/heads/main'
    uses: hwolf/workflows/.github/workflows/build.yml@main
    with:
      environment: "qa"
      sonar-token: XXXXX #"${{ secrets.SONAR_TOKEN }}"
