name: Build Pull Request
on:
  pull_request:

env:
  REVISION: "pr-${{ github.event.inputs.pr_number }}"

jobs:
  build:
    name: Build Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build-and-test.yml@main
        with:
          revision: $REVISION
