name: 'Build Pull Request'
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  build:
    name: 'Build Pull Request'
    uses: hwolf/workflows/build-and-test.yml@main
    with:
      revision: "pr-${{ github.event.pull_request.number }}"
      publish-image: false

  terraform:
    name: 'Validate Terraform Scripts'
    uses: hwolf/test/.github/workflows/verify-terraform.yml@main
