name: Build and Deploy Snapshot
on:
  push:
    branches:
      - main
      - "spring-boot-*"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
permissions:
  packages: write
jobs:
  build-and-deploy-snapshot:
    name: Build and Deploy Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Deploy Snapshot
        uses: ./.github/actions/build
        with:
          publish: "${{ secrets.GITHUB_TOKEN }}"
