name: Build Branch
on:
  push:
    branches:
      - main
      - "spring-boot-*"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - name: Set version
        run: |
          base="$(mvn help:evaluate -Dexpression=project.parent.version -q -DforceStdout)"
          version="$base-snapshot-$(date "+%Y%m%d-%H%M%S")"
          echo "version=$version" >> "$GITHUB_ENV"
      - uses: ./.github/actions/build-project
        with:
          version: "${{ env.version }}"
      - name: Create draft release
        run: |
          gh release create -d v-"${{ env.version }}"
        env:
          GH_TOKEN: ${{ github.token }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: ./.github/actions/deploy
        with:
          env: staging
          version: "${{env.version }}"
