name: Build Branch
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: staging

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - name: Set version
        run: |
          echo "version=$(date "+%Y%m%d-%H%M%S")" >> "$GITHUB_ENV"
      - uses: ./.github/actions/build-project
        with:
          version: "${{ env.version }}"
          publish-image: true
      #- uses: ./.github/actions/deploy
      #  with:
      #    env: staging
      #    version: "${{ env.version }}"

  publish-image:
    name: Publish Image
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Log in to the Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
        #  username: ${{ github.actor }}
        #  password: ${{ secrets.GITHUB_TOKEN }}

#  deploy-staging:
#    name: Deploy to Staging
#    runs-on: ubuntu-latest
#    needs:
#      - publish-image
#    environment: staging
#    steps:
#      - uses: ./.github/actions/deploy
#        with:
#          env: staging
#          version: "${{ env.version }}"
#
#  create-prerelease:
#    name: Create Prerelease
#    runs-on: ubuntu-latest
#    needs:
#      - build
#      - deploy-staging
#    steps:
#      - name: Create prerelease
#        run: |
#          gh release create -p --latest v-"${{ env.version }}"
#        env:
#          GH_TOKEN: ${{ github.token }}
