name: "Build Branch"
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - none
          - dev
          - test
        default: test
        description: Deploy to environment?

jobs:
  build:
    name: "Build"
    if: github.ref != 'refs/heads/main'
    uses: hwolf/workflows/.github/workflows/build.yml@main
    with:
      revision: "$(date +%Y%m%d)-${{ github.sha }}-${{ github.run_number }}"
      environment: "${{ inputs.environment || 'none' }}"
    secrets:
      SEC_1: ${{ secrets.SEC_1 }}
      SEC_2: ${{ secrets.SEC_1 }}