name: Build and Deploy Snapshot
on:
  push:
    branches:
      - main
      - "spring-boot-*"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  build-and-publish-snapshot:
    name: Build and Publish Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: ./.github/actions/setup-java
      - name: Set version
        run: |
          base="$(mvn help:evaluate -Dexpression=project.parent.version -q -DforceStdout)"
          version="$base-snapshot-$(date "+%Y%m%d-%H%M%S")"
          echo "version=$version" >> "$GITHUB_ENV"
      - name: Build
        uses: ./.github/actions/build-project
        with:
          version: "${{env.version }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy -Drevision="${{ env.version }}" -DskipTests
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
