name: "Build and deploy"
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - none
          - dev
          - test
          - qa
        default: test
        description: Deploy to environment?

jobs:
  build:
    name: "Build and deploy"
    uses: hwolf/workflows/build.yml@main
    with:
      environment: "${{ inputs.environment || 'qa' }}"
    secrets: inherit
