name: "Build Pull Request"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  build:
    name: "Build"
    if: github.ref != 'refs/heads/main'
    uses: hwolf/workflows/.github/workflows/build.yml@main
    with:
      environment: "none"
      sonar-token: "${{ secrets.SONAR_TOKEN }}"
