name: "Build Main"
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - none
          - dev
          - test
          - qa
        default: qa
        description: Deploy to environment?

jobs:
  build:
    name: "Build"
    if: github.ref == 'refs/heads/main'
    uses: hwolf/test/.github/workflows/build.yml@main
    with:
      revision: "$(date +%Y%m%d)-${{ github.run_number }}"
      publish-image: ${{ inputs.environment != 'none' }}
      environment: "${{ inputs.environment || 'qa' }}"
