name: "Build Branch"
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - none
          - dev
          - test
          - qa
        default: test
        description: Deploy to environment?

jobs:
  build:
    name: "Build"
    uses: hwolf/workflows/.github/workflows/build.yml@main
    with:
      environment: "${{ inputs.environment }}"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
