name: "Build and deploy"
run-name: "Build and deploy branch ${{ github.ref_name }} to ${{ inputs.environment || 'qa' }} by @${{ github.actor }}"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - none
          - dev
          - test
          - qa
        default: test
        description: Deploy to environment?

jobs:
  build:
    name: "Build and deploy"
    uses: hwolf/workflows/.github/workflows/build-and-deploy.yml@main
    with:
      environment: "${{ inputs.environment || 'qa' }}"
    secrets: inherit
