name: "Build pull request"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  build:
    name: "Build pull request"
    uses: hwolf/workflows/build.yml@main
    with:
      environment: "none"
    secrets: inherit
