name: 'Build Pull Request'
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  build:
    name: 'Build Pull Request'
    uses: hwolf/workflows/.github/workflows/build-and-test.yml@main
    with:
      revision: "pr-${{ github.event.pull_request.number }}"
      publish-image: true

  terraform:
    name: 'Validate Terraform Scripts'
    uses: hwolf/workflows/.github/workflows/verify-terraform.yml@main

  deploy:
    name: 'Deploy Pull Request'
    needs:
      - build
      - terraform
    uses: hwolf/workflows/.github/workflows/deploy.yml@main
    with:
      image-name: "${{ needs.build.outputs.image-name }}"
      environment: "dev"
