name: 'Build Pull Request'
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

env:
  REVISION: "pr-${{ github.event.inputs.pr_number }}"

jobs:
  build:
    name: 'Build Pull Request'
    uses: hwolf/test/.github/workflows/build-and-test.yml@test-1
    with:
      revision: ${{ env.REVISION }}
