name: "Build Main"
on:
  push:
    branches:
      - main

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: hwolf/workflows/test1@main
        with:
          inp1: AAAA
      - uses: hwolf/workflows/test2@main
        with:
          inp2: BBBB
  #build:
  #  name: "Build"
  #  if: github.ref == 'refs/heads/main'
  #  uses: hwolf/workflows/.github/workflows/build.yml@main
  #  with:
  #    environment: "qa"
  #    sonar-token: "${{ secrets.SONAR_TOKEN }}"
