name: Build Branch
on:
  push:
    branches:
      - main
      - "spring-boot-*"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - name: Set version
        run: |
          echo "version=$(date "+%Y%m%d-%H%M%S")" >> "$GITHUB_ENV"
      - uses: ./.github/actions/build-project
        with:
          version: "${{ env.version }}"
      - uses: ./.github/actions/deploy
        with:
          env: staging
          version: "${{ env.version }}"
      - name: Create prerelease release
        run: |
          gh release create -p v-"${{ env.version }}"
        env:
          GH_TOKEN: ${{ github.token }}
