name: "Build Pull Request"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  build:
    name: "Build"
    if: github.ref != 'refs/heads/main'
    uses: hwolf/workflows/.github/workflows/build.yml@main
    with:
      revision: "$(date +%Y%m%d)-${{ github.sha }}-${{ github.run_number }}"
      environment: "none"
    secrets: inherit
