name: "Build pull request"
run-name: "Build PR ${{ github.event.number }} (${{ github.ref_name }}) by @${{ github.actor }}"

concurrency:
  group: "build-pull-request"
  cancel-in-progress: false

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  build:
    name: "Build pull request"
    uses: hwolf/workflows/.github/workflows/build-and-deploy.yml@main
    with:
      environment: "none"
    secrets: inherit
