name: Cleanup
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
jobs:
  cleanup-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 10
          keep_minimum_runs: 6

  cleanup-prereleases:
    runs-on: ubuntu-latest
    steps:
      - name: Delete pre-releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 3
          delete_prerelease_only: true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#  cleanup-packages:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Delete old packages
#      uses: actions/delete-package-versions@v5
#      with:
#        package-name: 'test.test'
#        package-type: 'maven'
#        min-versions-to-keep: 2
#        ignore-versions: '^[0-9\.]+\-[0-9]+$'
