name: "Deploy to PRD"
on:
  workflow_dispatch:
#    inputs:
#      environment:
#        type: environment
#        description: Target environment

concurrency: prd

jobs:
  deploy-prod:
    name: "Deploy to PRD"
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - run: |
          echo Deploying ${{ github.ref }} to PRD
          echo "TODO ..."
