name: 'Deploy Pull Request'

on:
  issue_comment:
    types:
     - created

jobs:
  setup:
    name: Setup
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy') && github.event.issue.state == 'open'
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.getref.outputs.head_ref }}
      sha: ${{ steps.getref.outputs.head_sha }}
    steps:
      - uses: xt0rted/pull-request-comment-branch@v3
        id: getref
      - run: |
          echo "head_ref=${{ steps.getref.outputs.head_ref }}" >> $GITHUB_OUTPUT
          echo "head_sha=${{ steps.getref.outputs.head_sha }}" >> $GITHUB_OUTPUT
      - uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.getref.outputs.head_sha }}
          status: 'pending'
          token: '${{ secrets.GITHUB_TOKEN }}'
      - run: |
          echo "${{ toJson(steps.getref) }}"

  build:
    name: 'Build Pull Request'
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy') && github.event.issue.state == 'open'
    needs:
      - setup
    uses: hwolf/workflows/.github/workflows/build-and-test.yml@main
    with:
      ref: "${{ needs.setup.outputs.ref }}"
      revision: "pr-${{ github.event.issue.number }}-${{ github.run_number }}"
      publish-image: true

  deploy:
    name: 'Deploy Pull Request'
    needs:
      - build
      - setup
    uses: hwolf/workflows/.github/workflows/deploy.yml@main
    with:
      image-name: "${{ needs.build.outputs.image-name }}"
      environment: "${{ contains(github.event.comment.body, '/deploy:dev') && 'dev' || 'test' }}"
      ref: "${{ needs.setup.outputs.ref }}"

  finished:
    name: 'XXXX'
    runs-on: ubuntu-latest
    if: always()
    needs:
      - setup
      - deploy
    steps:
      - uses: myrotvorets/set-commit-status-action@master
        with:
          sha: "${{ needs.setup.outputs.sha }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
