name: Deploy Production
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: Environment
concurrency:
  group: ${{ inputs.environment }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo Branch ${{ github.ref_name }}
      - uses: ./.github/actions/deploy
        with:
          env: ${{ inputs.environment }}
          version: "${{ github.ref_name }}"
      - run: |
          echo "now=$(date '+%-d.%-m.%Y %-H:%M:%S')" >> $GITHUB_ENV
