name: Deploy Production
on:
  release:
    types:
      - released
concurrency:
  group: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo Branch $(git branch)
      - uses: ./.github/actions/deploy
        with:
          env: production
          version: "${{env.version }}"
