name: 'Deploy Pull Request'

on:
  issue_comment:
    types:
     - created

jobs:
  branch:
    name: Get Pull Request branch
    runs-on: ubuntu-latest
    steps:
      - uses: xt0rted/pull-request-comment-branch@v3
        id: branch
      - run: |
          echo "ref=${{ steps.branch.outputs.head_ref }}" >> $GITHUB_OUT
          cat $GITHUB_OUT
    outputs:
      ref: ${{ steps.branch.outputs.ref }}

  test:
    name: 'Build Pull Request'
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '@deploy')
    needs:
      - branch
    steps:
      - run: |
          echo "XX1=${{ needs.branch.outputs.ref }}"
          echo "XX2=${{ steps.branch.outputs.ref }}"

#  build:
#    name: 'Build Pull Request'
#    if: github.event.issue.pull_request && contains(github.event.comment.body, '@deploy')
#    needs:
#      - branch
#    uses: hwolf/test/.github/workflows/build-and-test.yml@test-1
#    with:
#      ref: ${{ jobs.branch.outputs.head_ref }}

#  deploy:
#    name: 'Deploy Pull Request'
#    needs:
#      - build
#      - branch
#    uses: hwolf/test/.github/workflows/deploy.yml@test-1
#    with:
#      image-name: "${{ needs.build.outputs.image-name }}"
#      environment: DEV
#      ref: ${{ jobs.branch.outputs.head_ref }}
