name: 'Deploy Pull Request'
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  build:
    name: 'Build Pull Request'
    uses: hwolf/test/.github/workflows/build-and-test.yml@test-1
    with:
      publish: true
      revision: "pr-${{ github.event.pull_request.number }}"

  deploy:
    name: 'Deploy Pull Request'
    needs: build
    uses: hwolf/test/.github/workflows/deploy.yml@test-1
    with:
      image-name: "${{ needs.build.outputs.image-name }}"
      environment: DEV
