name: "Deploy to PRD"
on:
  workflow_dispatch:

jobs:
  revision:
    name: 'Find revision'
    runs-on: ubuntu-latest
    outputs:
      revision: ${{ steps.rev.outputs.revision }}
    steps:
      - id: rev
        run: |
          ref="${{ github.ref }}"
          echo "revision=${ref#"refs/tags/qa-deployed-"}" >> $GITHUB_OUTPUT

  dump:
    name: "Dump"
    needs:
      - revision
    runs-on: ubuntu-latest
    steps:
      - run: echo "XXX ${{ needs.revision.outputs.revision }}"

  deploy-prod:
    name: "Deploy to PRD"
    needs:
      - revision
    uses: hwolf/workflows/.github/workflows/deploy.yml@main
    with:
      revision: "${{ needs.revision.outputs.revision }}"
      environment: "prd"
