name: 'Deploy Pull Request'

on:
  issue_comment:
    types:
     - created

jobs:
  branch:
    name: Get Pull Request branch
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.getRef.outputs.head_ref }}
    steps:
      - uses: xt0rted/pull-request-comment-branch@v3
        id: getref
      - run: |
          echo "head_ref=${{ steps.getref.outputs.head_ref }}" >> $GITHUB_OUTPUT
          echo "head_ref=${{ steps.getref.outputs.head_ref }}"
          echo "steps=${{ toJson(steps) }}"

  build:
    name: 'Build Pull Request'
    if: github.event.issue.pull_request && contains(github.event.comment.body, '@deploy')
    needs:
      - branch
    uses: hwolf/test/.github/workflows/build-and-test.yml@test-1
    with:
      ref: ${{ needs.branch.outputs.ref }}
      revision: pr-${{ github.event.issue.number }}-${{ github.run_number }}

  deploy:
    name: 'Deploy Pull Request'
    needs:
      - build
      - branch
    uses: hwolf/test/.github/workflows/deploy.yml@test-1
    with:
      image-name: "${{ needs.build.outputs.image-name }}"
      environment: DEV
      ref: ${{ needs.branch.outputs.ref }}
