name: "Deploy to PRD"
run-name: "Deploy to prd by @${{ github.actor }}"

on:
  deployment

#permissions: write-all

jobs:
#  revision:
#    name: 'Find revision'
#    runs-on: ubuntu-latest
#    outputs:
#      revision: ${{ steps.rev.outputs.revision }}
#    steps:
#      - id: rev
#        run: |
#          ref="${{ github.ref_name }}"
#          echo "revision=${ref#"qa-deployed-"}" >> $GITHUB_OUTPUT

  deploy-prod:
    name: "Deploy to PRD"
#    needs:
#      - revision
    uses: hwolf/workflows/.github/workflows/deploy.yml@main
    with:
      image-tag: "${{ github.sha }}"
#      revision: "${{ needs.revision.outputs.revision }}"
      environment: "prd"
