name: "Deploy to PRD"
on:
  workflow_dispatch:

jobs:
  revision:
    name: 'Revision'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "revision=${GITHUB_REF#"refs/tags/qa-deployed-"}" >> $GITHUB_ENV

  deploy-prod:
    name: "Deploy to PRD"
    uses: hwolf/workflows/.github/workflows/deploy.yml@main
    with:
      revision: "${{ env.revision }}"
      environment: "prd"
