name: 'Deploy Pull Request'

on:
  issue_comment:
    types:
     - created

jobs:
  setup:
    name: Setup
    if: github.event.issue.pull_request && contains(github.event.comment.body, '@deploy') && github.event.issue.state == 'open'
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.getRef.outputs.head_ref }}
    steps:
      - run: |
          echo "${{ contains(github.event.comment.body, '@deploy dev') && 'DEV' || 'TEST' }}"
      - uses: xt0rted/pull-request-comment-branch@v3
        id: getref
      - run: |
          echo "head_ref=${{ steps.getref.outputs.head_ref }}" >> $GITHUB_OUTPUT

  build:
    name: 'Build Pull Request'
    if: github.event.issue.pull_request && contains(github.event.comment.body, '@deploy') && github.event.issue.state == 'open'
    needs:
      - setup
    uses: hwolf/test/.github/workflows/build-and-test.yml@test-1
    with:
      ref: ${{ needs.setup.outputs.ref }}
      revision: pr-${{ github.event.issue.number }}-${{ github.run_number }}

  deploy:
    name: 'Deploy Pull Request'
    if: github.event.issue.pull_request && contains(github.event.comment.body, '@deploy') && github.event.issue.state == 'open'
    needs:
      - build
      - setup
    uses: hwolf/test/.github/workflows/deploy.yml@test-1
    with:
      image-name: "${{ needs.build.outputs.image-name }}"
      environment: 'TEST'
      ref: ${{ needs.setup.outputs.ref }}
