name: "Deploy to PRD"
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Target environment

concurrency: ${{ inputs.environment }}

jobs:
  deploy-prod:
    name: "Deploy to ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: |
          echo Deploying ${{ github.ref }} to ${{ inputs.environment }}
          echo "TODO ..."
