name: Deploy Production
on:
  release:
    types:
      - created
concurrency:
  group: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo Branch $(git branch) ${{ github.ref_name }}
      - uses: ./.github/actions/deploy
        with:
          env: production
          version: "${{ github.ref_name }}"
