name: Build and Deploy Release
on:
  workflow_dispatch
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
jobs:
  build-and-publish:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: ./.github/actions/setup-java
      - name: Set version
        run: |
          base="$(mvn help:evaluate -Dexpression=project.parent.version -q -DforceStdout)"
          version="$(git tag --sort=-v:refname | grep v$base || true | head -n 1)"
          version="${version:-$base-0}"
          version="${version%%-*}-$(expr ${version#*-} + 1)"
          echo "version=$version" >> "$GITHUB_ENV"
      - name: Build Project
        uses: ./.github/actions/build-project
        with:
          version: "${{env.version }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy -Drevision="${{ env.version }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Publish GitHub Release
        run: gh release create ${{ format('v{0}', env.version) }} --notes "Test"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
