name: Build and Deploy Release
on:
  workflow_dispatch
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
jobs:
  build-and-publish:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: ./.github/actions/setup-java
      - name: Set version
        run: |
          base="$(mvn help:evaluate -Dexpression=project.parent.version -q -DforceStdout)"
          version="$(git tag --sort=-v:refname | (grep -e "^v$base" || true) | head -n 1)"
          echo X $version
          version="${version:1}"
          version="${version:-$base-0}"
          version="${version%%-*}"-"$(expr ${version#*-} + 1)"
          echo version="$version" >> "$GITHUB_ENV"
      - name: Build Project
        uses: ./.github/actions/build-project
        with:
          version: "${{env.version }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy -Drevision="${{ env.version }}" -DskipTests
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Publish JavaDocs
        run: "echo TODO: Publish JavaDocs"
      - name: Generate Changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --current
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}
      - name: Publish GitHub Release
        run: gh release create "v${{ env.version }}" --title "v${{ env.version }}" --notes-file CHANGES.md
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
