name: Build and Deploy Release
on:
  workflow_dispatch
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
permissions:
  packages: write
jobs:
  build-and-publish:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Publish
        uses: ./.github/actions/build-and-publish
        with:
          release: final
          token: "${{ secrets.GITHUB_TOKEN }}"
