name: 'Sample'
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - none
          - dev
          - test
          - qa
          - prd
        default: none
        description: Deploy to environment?

env:
  ENV: ${{ inputs.environment || 'none' }}

jobs:
  parameters:
    name: Parameters
    runs-on: ubuntu-latest
    steps:
      - name: GitHub
        run: echo "Github ${{ toJson(github) }}"
      - name: Inputs
        run: echo "Inputs ${{ toJson(inputs) }}"
      - name: Environment
        run: env | sort

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building..."

  deploy:
    name: Deploy to $ENV
    if: env.ENV != 'none'
    runs-on: ubuntu-latest
    needs: build
    environment: $ENV
    steps:
      - run: echo "Deploying to $ENV..."
      - run: env | sort