name: 'Sample'
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
  workflow_call:
    inputs:
      environment:
        type: environment
        required: false
        description: Deploy to environment?

jobs:
  parameters:
    name: 'Parameters'
    runs-on: ubuntu-latest
    steps:
    - name: GitHub
      run: echo "Github ${{ toJson(github) }}"
    - name: Inputs
      run: echo "Github ${{ toJson(inputs) }}"
    - name: Environment
      run: |
          env | sort
