name: 'SBOM'
on:
  deployment:

concurrency: ${{ github.event.deployment.environment }}

jobs:
  sbom:
    name: 'Upload SBOM for environment ${{ github.event.deployment.environment }}'
    runs-on: ubuntu-latest
    steps:
      - name: 'Generate SBOM'
        run: |
          echo "TODO ..."

      - name: 'Upload SBOM'
        run: |
          echo "TODO ..."
