name: 'Test'

on:
  pull_request_review_comment:
    types:
     - created
     - edited

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Github=${{ toJson(github) }}"