name: 'Verify Terraform'
on:
  workflow_call:
    inputs:
      revision:
        type: string
        required: true
      service-folder:
        type: string
        default: '.'
      image-name:
        type: string
      environment:
        type: string
        default: DEV

jobs:
  verify-terraform:
    name: 'Verify Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2
          terraform_wrapper: false

      - name: 'Validate Terraform'
        run: |
          echo "TODO"
